 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: votingapp-deployment
   labels:
     name: votingapp-deployment
     app: demo-voting-app
 spec:
   template:
     metadata:
       name: voting-app-pod
       labels:
         name: voting-app-pod
         app: demo-voting-app
     spec:
         containers:
           - name: voting-app
             image: dockersamples/examplevotingapp_vote
             ports:
               - containerPort: 80
   replicas: 1
   selector:
     matchLabels:
       name: voting-app-pod
       app: demo-voting-app